version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: windows95-js
    path: ./.github/config/windows95-js.dict
    addWords: true
dictionaries:
  - windows95-js
words: []
ignoreWords: []
import: []
