version: '0.2'
ignorePaths:
  - dist/
  - src/renderer/lib/libv86.js
  - '*.wasm'
  - '*.lock'
dictionaryDefinitions:
  - name: js-win95
    path: ./.github/config/js-win95.dict
    addWords: true
dictionaries:
  - js-win95
words: []
ignoreWords: []
import: []
